#!/bin/bash
cd ./twoOpt
python2.7 setup.py build_ext -i > log
if [ "$?" = 0 ]
then
    cp _twoOpt.c ../NN_KDTree/_twoOpt.c
    cp _twoOpt.so ../NN_KDTree/_twoOpt.so
    cd ..
    echo "Test Case 7"
    nohup python2.7 main.py ./tsp_test_cases/test-input-7.txt
    python2.7 ./util/tsp-verifier.py ./tsp_test_cases/test-input-7.txt ./tsp_test_cases/test-input-7.txt.tour
else
    cat log
fi
